//ActionTypes
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const CREATE_CHILDTOPIC = "CREATE_CHILDTOPIC";
export const RETRIEVE_CHILTOPIC = "RETRIEVE_CHILDTOPIC";
export const UPDATE_CHILDTOPIC = "UPDATE_CHILDTOPIC";
export const DELETE_CHILDTOPIC = "DELETE_CHILDTOPIC";
export const DELETE_ALL_CHILDTOPIC = "DELETE_ALL_CHILDTOPIC";
