//ActionTypes
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const REFRESH_TOKEN = "REFRESH_TOKEN";

export const CREATE_CHILDTOPIC = "CREATE_CHILDTOPIC";
export const RETRIEVE_CHILTOPIC = "RETRIEVE_CHILDTOPIC";
export const RETRIEVE_CHILDTOPICAUTHOR = "RETRIEVE_CHILDTOPICAUTHOR";
export const UPDATE_CHILDTOPIC = "UPDATE_CHILDTOPIC";
export const DELETE_CHILDTOPIC = "DELETE_CHILDTOPIC";
export const DELETE_ALL_CHILDTOPIC = "DELETE_ALL_CHILDTOPIC";

export const CREATE_PARENTTOPIC = "CREATE_PARENTTOPIC";
export const RETRIEVE_PARENTTOPIC = "RETRIEVE_PARENTTOPIC";
export const RETRIEVE_PARENTTOPICAUTHOR = "RETRIEVE_PARENTTOPICAUTHOR";
export const UPDATE_PARENTTOPIC = "UPDATE_PARENTTOPIC";
export const DELETE_PARENTTOPIC = "DELETE_PARENTTOPIC";
export const DELETE_ALL_PARENTTOPIC = "DELETE_ALL_PARENTTOPIC";

export const DELETE_LISTTOPIC = "DELETE_LISTTOPIC";
